services:
  docker-proxy:
    image: ghcr.io/antimatter-studios/docker-proxy:latest
    container_name: docker-proxy
    build: .
    restart: always
    volumes:
      # DEV MODE: uncomment this to quickly edit the 200, 503 templates
      - ./html:/etc/nginx/html
      # DEV MODE: uncomment this to let you edit the entire app directory on the fly
      - ./:/app
      # Shared volume for management socket
      - management:/var/run/proxy
      # Shared volume for TLS certificates (future Let's Encrypt)
      - certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"

volumes:
  management:
  certs:
